Pim\Bundle\CatalogBundle\Model\ProductMedia:
    type: embeddedDocument
    fields:
        id:
            id: true
        filename:
            type: string
        originalFilename:
            type: string
        mimeType:
            type: string
        #TODO: drop useless columns
        #TODO: link to files
